name:                clutter
version:             0.1.1.0
github:              "LATBauerdick/clutter-hs"
license:             BSD-3-Clause
author:              "LATBauerdick"
maintainer:          "github@bauerdick.org"
copyright:           "2022 LATBauerdick"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            server for Clutter
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/LATBauerdick/clutter-hs#readme>

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
  - base >= 4.14 && < 5
  - relude >= 1.0.0.0
  - aeson
  - servant
  - servant-server
  - servant-client
  - wai
  - warp
  - lucid
  - HTTP
  - http-media
  - hashable
  - bytestring
  - vector
  - containers
  - text
  - raw-strings-qq
  - http-client
  - http-client-tls
  - time

ghc-options:
  - -Wall
  - -fno-warn-unused-binds
  - -fwrite-ide-info
  - -hiedir=.hie

library:
  source-dirs: src

executables:
  clutter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clutter

tests:
  clutter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - clutter
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
