#!/usr/bin/env python
#
# run this after nix develop --command zsh
#
####!/usr/bin/env nix-shell
####!nix-shell -i python3 -p "python3.withPackages(ps: [ ps.requests ps.python-dateutil ])"

# needs git clone https://github.com/tamland/python-tidal

#####!/usr/bin/env python3
#### this is outdated, now works with the latest versions of tidalapi
#### How To get the tidalapi package vs 0.7.0:
####   python3 -m pip install git+https://github.com/tamland/python-tidal@ee120d94d897f6f6ee644fd835a35fb68942b331
#### or check out from github:
####   git clone https://github.com/tamland/python-tidal
####   cd python-tidal
####   git checkout ee120d94d897f6f6ee644fd835a35fb68942b331
####
import sys, subprocess
sys.path.append('./python-tidal') #the directory that contains my_pkg
####print(sys.path)
import tidalapi
session = tidalapi.Session()
# new oauth-based authentication
# Will run until you visit the printed url and link your account
session.login_oauth_simple()
# then print out the access_token etc
print(session.user.username)
with open('.tok-tidal.dat', 'w') as f:
    print(session.user.id, file=f)
    print(session.session_id, file=f)
    print(session.country_code, file=f)
    print(session.access_token, file=f)

result = subprocess.run('{ head -n -4 tok.dat && cat .tok-tidal.dat; } > tok.dat.tmp && mv tok.dat.tmp tok.dat', shell=True, capture_output=True, text=True)

print(result.stdout)
