name:                backend
version:             0.1.0.0
github:              "LATBauerdick/backend"
license:             BSD3
author:              "LATBauerdick"
maintainer:          "gitbub@bauerdick.org"
copyright:           "2020 LATBauerdick"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            backend for Clutter
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/LATBauerdick/backend#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- lucid
- http-media
- bytestring
- utf8-string
- vector
- containers
- cassava
- text
- raw-strings-qq
- mtl
- http-conduit
- http-types
- http-client
- http-client-tls
- authenticate-oauth
- time
- yaml

library:
  source-dirs: src

executables:
  backend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - backend

tests:
  backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - backend
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
